from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.sheet import Sheet, SheetItem

STRIVERS_SDE_SHEET_ITEMS = [
    # Day 1: Arrays
    {"pattern": "Day 1: Arrays", "position": 1, "title": "Set Matrix Zeroes", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/set-matrix-zeroes/", "article_url": "https://takeuforward.org/data-structure/set-matrix-zero/", "description": "Set entire row and column to 0 if an element is 0."},
    {"pattern": "Day 1: Arrays", "position": 2, "title": "Pascal's Triangle", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/pascals-triangle/", "article_url": "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/", "description": "Generate the first numRows of Pascal's triangle."},
    {"pattern": "Day 1: Arrays", "position": 3, "title": "Next Permutation", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/next-permutation/", "article_url": "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/", "problem_slug": "next-permutation", "description": "Rearrange numbers into the lexicographically next greater permutation."},
    {"pattern": "Day 1: Arrays", "position": 4, "title": "Maximum Subarray (Kadane's Algorithm)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/maximum-subarray/", "article_url": "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/", "problem_slug": "maximum-subarray", "description": "Find the contiguous subarray with the largest sum."},
    {"pattern": "Day 1: Arrays", "position": 5, "title": "Sort Colors (Dutch National Flag)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/sort-colors/", "article_url": "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/", "description": "Sort an array with 0s, 1s, and 2s in-place in linear time."},
    {"pattern": "Day 1: Arrays", "position": 6, "title": "Stock Buy and Sell", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "article_url": "https://takeuforward.org/data-structure/stock-buy-and-sell/", "problem_slug": "best-time-to-buy-and-sell-stock", "description": "Maximize profit by buying and selling a stock on different days."},

    # Day 2: Arrays Part-II
    {"pattern": "Day 2: Arrays Part-II", "position": 1, "title": "Rotate Matrix / Image", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/rotate-image/", "article_url": "https://takeuforward.org/data-structure/rotate-image-by-90-degree/", "description": "Rotate an n x n 2D matrix by 90 degrees clockwise in-place."},
    {"pattern": "Day 2: Arrays Part-II", "position": 2, "title": "Merge Overlapping Subintervals", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/merge-intervals/", "article_url": "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/", "problem_slug": "merge-intervals", "description": "Merge all overlapping intervals."},
    {"pattern": "Day 2: Arrays Part-II", "position": 3, "title": "Merge Two Sorted Arrays Without Extra Space", "difficulty": "hard", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1", "article_url": "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/", "description": "Merge two sorted arrays in-place without extra space."},
    {"pattern": "Day 2: Arrays Part-II", "position": 4, "title": "Find Missing and Repeating Number", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1", "article_url": "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/", "description": "Find the repeating and missing number in an array from 1 to N."},
    {"pattern": "Day 2: Arrays Part-II", "position": 5, "title": "Count Inversions in Array", "difficulty": "hard", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1", "article_url": "https://takeuforward.org/data-structure/count-inversions-in-an-array/", "description": "Count inversion pairs (i < j and A[i] > A[j]) using merge sort."},
    {"pattern": "Day 2: Arrays Part-II", "position": 6, "title": "Find Duplicate in Array (Floyd's Tortoise)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/find-the-duplicate-number/", "article_url": "https://takeuforward.org/data-structure/find-the-duplicate-in-an-array-of-n1-integers/", "description": "Find the duplicate number in an array containing N+1 integers."},

    # Day 3: Arrays/Math
    {"pattern": "Day 3: Arrays/Math", "position": 1, "title": "Search in a 2D Matrix", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/search-a-2d-matrix/", "article_url": "https://takeuforward.org/data-structure/search-in-a-2d-matrix/", "description": "Search target in m x n matrix where rows & columns are sorted."},
    {"pattern": "Day 3: Arrays/Math", "position": 2, "title": "Pow(x, n)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/powx-n/", "article_url": "https://takeuforward.org/data-structure/calculate-double-x-n/", "description": "Implement power function x^n using binary exponentiation in O(log n)."},
    {"pattern": "Day 3: Arrays/Math", "position": 3, "title": "Majority Element (> N/2 times)", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/majority-element/", "article_url": "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/", "description": "Find majority element appearing more than N/2 times using Boyer-Moore Voting."},
    {"pattern": "Day 3: Arrays/Math", "position": 4, "title": "Majority Element II (> N/3 times)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/majority-element-ii/", "article_url": "https://takeuforward.org/data-structure/majority-elements-n-3-times-find-the-elements-that-appear-more-than-n-3-times-in-the-array/", "description": "Find all elements that appear more than N/3 times in array."},
    {"pattern": "Day 3: Arrays/Math", "position": 5, "title": "Grid Unique Paths", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/unique-paths/", "article_url": "https://takeuforward.org/data-structure/grid-unique-paths-count-paths-from-left-top-to-right-bottom-of-a-m-x-n-matrix/", "description": "Find total unique paths from top-left to bottom-right of m x n grid."},
    {"pattern": "Day 3: Arrays/Math", "position": 6, "title": "Reverse Pairs", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/reverse-pairs/", "article_url": "https://takeuforward.org/data-structure/count-reverse-pairs/", "description": "Count reverse pairs where i < j and nums[i] > 2 * nums[j]."},

    # Day 4: Arrays/Hashing
    {"pattern": "Day 4: Arrays/Hashing", "position": 1, "title": "Two Sum", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/two-sum/", "article_url": "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/", "problem_slug": "two-sum", "description": "Find indices of two numbers that add up to target."},
    {"pattern": "Day 4: Arrays/Hashing", "position": 2, "title": "4Sum", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/4sum/", "article_url": "https://takeuforward.org/data-structure/4-sum-find-all-unique-quadruplets-that-add-up-to-target-value/", "description": "Find all unique quadruplets that sum to target."},
    {"pattern": "Day 4: Arrays/Hashing", "position": 3, "title": "Longest Consecutive Sequence", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/longest-consecutive-sequence/", "article_url": "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/", "description": "Find length of longest consecutive elements sequence in O(n) time."},
    {"pattern": "Day 4: Arrays/Hashing", "position": 4, "title": "Largest Subarray with 0 Sum", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1", "article_url": "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/", "description": "Find length of longest contiguous subarray whose sum is 0."},
    {"pattern": "Day 4: Arrays/Hashing", "position": 5, "title": "Count Subarrays with Given XOR K", "difficulty": "medium", "platform": "gfg", "problem_url": "https://www.interviewbit.com/problems/subarray-with-given-xor/", "article_url": "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/", "description": "Count total subarrays having bitwise XOR equal to K."},
    {"pattern": "Day 4: Arrays/Hashing", "position": 6, "title": "Longest Substring Without Repeating Characters", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "article_url": "https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/", "problem_slug": "longest-substring-without-repeating", "description": "Find length of longest substring with no duplicate characters."},

    # Day 5: Linked List
    {"pattern": "Day 5: Linked List", "position": 1, "title": "Reverse Linked List", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/reverse-linked-list/", "article_url": "https://takeuforward.org/data-structure/reverse-a-linked-list/", "problem_slug": "reverse-linked-list", "description": "Reverse a singly linked list."},
    {"pattern": "Day 5: Linked List", "position": 2, "title": "Middle of the Linked List", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/middle-of-the-linked-list/", "article_url": "https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/", "problem_slug": "middle-of-linked-list", "description": "Find middle node of a linked list using fast & slow pointers."},
    {"pattern": "Day 5: Linked List", "position": 3, "title": "Merge Two Sorted Lists", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/merge-two-sorted-lists/", "article_url": "https://takeuforward.org/data-structure/merge-two-sorted-linked-lists/", "description": "Merge two sorted linked lists into one sorted list."},
    {"pattern": "Day 5: Linked List", "position": 4, "title": "Remove Nth Node From End of List", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "article_url": "https://takeuforward.org/data-structure/remove-n-th-node-from-the-end-of-a-linked-list/", "description": "Remove the nth node from the end of a singly linked list."},
    {"pattern": "Day 5: Linked List", "position": 5, "title": "Add Two Numbers as Linked Lists", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/add-two-numbers/", "article_url": "https://takeuforward.org/data-structure/add-two-numbers-represented-as-linked-lists/", "description": "Add two numbers represented by linked lists in reverse digits order."},
    {"pattern": "Day 5: Linked List", "position": 6, "title": "Delete Node in a Linked List", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/delete-node-in-a-linked-list/", "article_url": "https://takeuforward.org/data-structure/delete-given-node-in-a-linked-list-o1-approach/", "description": "Delete a given node in a singly linked list in O(1) time without head pointer."},

    # Day 6: Linked List Part-II
    {"pattern": "Day 6: Linked List Part-II", "position": 1, "title": "Intersection Point of Two Linked Lists", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/intersection-of-two-linked-lists/", "article_url": "https://takeuforward.org/data-structure/find-intersection-of-two-linked-lists/", "description": "Find node where two singly linked lists intersect."},
    {"pattern": "Day 6: Linked List Part-II", "position": 2, "title": "Detect Cycle in Linked List", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/linked-list-cycle/", "article_url": "https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/", "problem_slug": "linked-list-cycle", "description": "Detect if a linked list has a cycle using Floyd's Tortoise & Hare."},
    {"pattern": "Day 6: Linked List Part-II", "position": 3, "title": "Reverse Nodes in k-Group", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/reverse-nodes-in-k-group/", "article_url": "https://takeuforward.org/data-structure/reverse-linked-list-in-groups-of-size-k/", "description": "Reverse nodes of linked list k at a time."},
    {"pattern": "Day 6: Linked List Part-II", "position": 4, "title": "Palindrome Linked List", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/palindrome-linked-list/", "article_url": "https://takeuforward.org/data-structure/check-if-given-linked-list-is-plaindrome/", "description": "Check if a singly linked list is a palindrome in O(n) time and O(1) space."},
    {"pattern": "Day 6: Linked List Part-II", "position": 5, "title": "Find Cycle Starting Point in Linked List", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/linked-list-cycle-ii/", "article_url": "https://takeuforward.org/data-structure/find-the-starting-point-of-the-loop-in-linked-list/", "description": "Return the node where cycle begins in a linked list."},
    {"pattern": "Day 6: Linked List Part-II", "position": 6, "title": "Flattening a Linked List", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1", "article_url": "https://takeuforward.org/data-structure/flattening-a-linked-list/", "description": "Flatten a multi-level linked list into a single sorted list."},

    # Day 7: Linked List & 2 Pointers
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 1, "title": "Rotate Linked List", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/rotate-list/", "article_url": "https://takeuforward.org/data-structure/rotate-a-linked-list/", "description": "Rotate linked list to right by k places."},
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 2, "title": "Clone Linked List with Random Pointer", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/copy-list-with-random-pointer/", "article_url": "https://takeuforward.org/data-structure/clone-linked-list-with-random-and-next-pointer/", "description": "Deep copy linked list with next and random pointers in O(1) extra space."},
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 3, "title": "3Sum", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/3sum/", "article_url": "https://takeuforward.org/data-structure/3-sum-find-all-unique-triplets-that-add-up-to-zero/", "problem_slug": "three-sum", "description": "Find all unique triplets that sum to zero."},
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 4, "title": "Trapping Rain Water", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/trapping-rain-water/", "article_url": "https://takeuforward.org/data-structure/trapping-rainwater/", "problem_slug": "trapping-rain-water", "description": "Compute trapped rain water between elevation bars."},
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 5, "title": "Remove Duplicates from Sorted Array", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "article_url": "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/", "description": "Remove duplicate elements in-place from sorted array."},
    {"pattern": "Day 7: Linked List & 2 Pointers", "position": 6, "title": "Max Consecutive Ones", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/max-consecutive-ones/", "article_url": "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/", "description": "Find maximum number of consecutive 1s in a binary array."},

    # Day 8: Greedy Algorithm
    {"pattern": "Day 8: Greedy Algorithm", "position": 1, "title": "N Meetings in One Room", "difficulty": "easy", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1", "article_url": "https://takeuforward.org/data-structure/n-meetings-in-one-room/", "description": "Find maximum number of meetings that can be performed in one room."},
    {"pattern": "Day 8: Greedy Algorithm", "position": 2, "title": "Minimum Platforms Required", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1", "article_url": "https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/", "description": "Find minimum platforms needed so no train waits at a railway station."},
    {"pattern": "Day 8: Greedy Algorithm", "position": 3, "title": "Job Sequencing Problem", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1", "article_url": "https://takeuforward.org/data-structure/job-sequencing-problem/", "description": "Find maximum profit from jobs executed before deadlines."},
    {"pattern": "Day 8: Greedy Algorithm", "position": 4, "title": "Fractional Knapsack", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1", "article_url": "https://takeuforward.org/data-structure/fractional-knapsack-problem-greedy-approach/", "description": "Maximize total value in knapsack by taking fractions of items."},
    {"pattern": "Day 8: Greedy Algorithm", "position": 5, "title": "Minimum Coins (Greedy)", "difficulty": "easy", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/number-of-coins1824/1", "article_url": "https://takeuforward.org/data-structure/find-minimum-number-of-coins/", "description": "Find minimum currency notes/coins to make change for V rupees."},

    # Day 9: Recursion
    {"pattern": "Day 9: Recursion", "position": 1, "title": "Subset Sums", "difficulty": "easy", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/subset-sums2234/1", "article_url": "https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/", "description": "Print sums of all subsets of a given array in sorted order."},
    {"pattern": "Day 9: Recursion", "position": 2, "title": "Subsets II", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/subsets-ii/", "article_url": "https://takeuforward.org/data-structure/subset-ii-print-all-unique-subsets/", "description": "Return all unique subsets from array containing duplicates."},
    {"pattern": "Day 9: Recursion", "position": 3, "title": "Combination Sum I", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/combination-sum/", "article_url": "https://takeuforward.org/data-structure/combination-sum-1/", "description": "Find all unique combinations summing to target (unlimited uses allowed)."},
    {"pattern": "Day 9: Recursion", "position": 4, "title": "Combination Sum II", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/combination-sum-ii/", "article_url": "https://takeuforward.org/data-structure/combination-sum-ii-find-all-unique-combinations/", "description": "Find unique combinations summing to target (each element used once)."},
    {"pattern": "Day 9: Recursion", "position": 5, "title": "Palindrome Partitioning", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/palindrome-partitioning/", "article_url": "https://takeuforward.org/data-structure/palindrome-partitioning/", "description": "Partition string such that every substring is a palindrome."},

    # Day 10: Recursion & Backtracking
    {"pattern": "Day 10: Recursion & Backtracking", "position": 1, "title": "Permutations of Array", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/permutations/", "article_url": "https://takeuforward.org/data-structure/print-all-permutations-of-a-string-array/", "description": "Return all possible permutations of an array of distinct integers."},
    {"pattern": "Day 10: Recursion & Backtracking", "position": 2, "title": "N-Queens Problem", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/n-queens/", "article_url": "https://takeuforward.org/data-structure/n-queen-problem-backtracking/", "description": "Place N queens on N x N chessboard so no two queens attack each other."},
    {"pattern": "Day 10: Recursion & Backtracking", "position": 3, "title": "Sudoku Solver", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/sudoku-solver/", "article_url": "https://takeuforward.org/data-structure/sudoku-solver/", "description": "Solve a 9x9 Sudoku puzzle using backtracking."},
    {"pattern": "Day 10: Recursion & Backtracking", "position": 4, "title": "M-Coloring Problem", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1", "article_url": "https://takeuforward.org/data-structure/m-coloring-problem/", "description": "Determine if graph nodes can be colored using M colors with no adjacent same colors."},
    {"pattern": "Day 10: Recursion & Backtracking", "position": 5, "title": "Rat in a Maze", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1", "article_url": "https://takeuforward.org/data-structure/rat-in-a-maze/", "description": "Find all possible paths for rat to move from (0,0) to (N-1,N-1)."},

    # Day 11: Binary Search
    {"pattern": "Day 11: Binary Search", "position": 1, "title": "N-th Root of an Integer", "difficulty": "easy", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/find-nth-root-of-m5843/1", "article_url": "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/", "description": "Find the nth root of integer m using binary search."},
    {"pattern": "Day 11: Binary Search", "position": 2, "title": "Single Element in Sorted Array", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/single-element-in-a-sorted-array/", "article_url": "https://takeuforward.org/data-structure/search-single-element-in-a-sorted-array/", "description": "Find single element appearing once in sorted array where all others appear twice."},
    {"pattern": "Day 11: Binary Search", "position": 3, "title": "Search in Rotated Sorted Array", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/search-in-rotated-sorted-array/", "article_url": "https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/", "problem_slug": "search-in-rotated-sorted-array", "description": "Search target in rotated sorted array in O(log n)."},
    {"pattern": "Day 11: Binary Search", "position": 4, "title": "Median of Two Sorted Arrays", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/median-of-two-sorted-arrays/", "article_url": "https://takeuforward.org/data-structure/median-of-two-sorted-arrays-of-different-sizes/", "problem_slug": "median-of-two-sorted-arrays", "description": "Find median of two combined sorted arrays in O(log(min(N,M)))."},
    {"pattern": "Day 11: Binary Search", "position": 5, "title": "Book Allocation Problem", "difficulty": "hard", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1", "article_url": "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/", "description": "Allocate books to M students such that maximum pages allocated to a student is minimized."},

    # Day 12: Heaps
    {"pattern": "Day 12: Heaps", "position": 1, "title": "Kth Largest Element in an Array", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/kth-largest-element-in-an-array/", "article_url": "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-an-array/", "problem_slug": "kth-largest-element", "description": "Find the kth largest element in an unsorted array using min-heap."},
    {"pattern": "Day 12: Heaps", "position": 2, "title": "Find Median from Data Stream", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/find-median-from-data-stream/", "article_url": "https://takeuforward.org/data-structure/find-median-from-data-stream/", "description": "Design data structure supporting median retrieval in real-time stream using max & min heap."},
    {"pattern": "Day 12: Heaps", "position": 3, "title": "Top K Frequent Elements", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/top-k-frequent-elements/", "article_url": "https://takeuforward.org/data-structure/top-k-frequent-elements-in-array/", "problem_slug": "top-k-frequent-elements", "description": "Find k most frequent elements in array."},

    # Day 13: Stack & Queue
    {"pattern": "Day 13: Stack & Queue", "position": 1, "title": "Implement Stack using Queues", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/implement-stack-using-queues/", "article_url": "https://takeuforward.org/data-structure/implement-stack-using-single-queue/", "description": "Implement LIFO stack using queue operations."},
    {"pattern": "Day 13: Stack & Queue", "position": 2, "title": "Implement Queue using Stacks", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/implement-queue-using-stacks/", "article_url": "https://takeuforward.org/data-structure/implement-queue-using-stack/", "description": "Implement FIFO queue using stack operations."},
    {"pattern": "Day 13: Stack & Queue", "position": 3, "title": "Valid Parentheses", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/valid-parentheses/", "article_url": "https://takeuforward.org/data-structure/check-for-balanced-parentheses/", "problem_slug": "valid-parentheses", "description": "Check if string of brackets is valid and properly balanced."},

    # Day 14: Stack & Queue Part-II
    {"pattern": "Day 14: Stack & Queue Part-II", "position": 1, "title": "LRU Cache Implementation", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/lru-cache/", "article_url": "https://takeuforward.org/data-structure/lru-cache-implementation/", "description": "Design LRU cache supporting get and put in O(1) time using hash map & doubly linked list."},
    {"pattern": "Day 14: Stack & Queue Part-II", "position": 2, "title": "LFU Cache Implementation", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/lfu-cache/", "article_url": "https://takeuforward.org/data-structure/lfu-cache-implementation/", "description": "Design LFU cache supporting get and put in O(1) time."},
    {"pattern": "Day 14: Stack & Queue Part-II", "position": 3, "title": "Largest Rectangle in Histogram", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/largest-rectangle-in-histogram/", "article_url": "https://takeuforward.org/data-structure/area-of-largest-rectangle-in-histogram/", "description": "Find area of largest rectangle in histogram using monotonic stack."},
    {"pattern": "Day 14: Stack & Queue Part-II", "position": 4, "title": "Sliding Window Maximum", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/sliding-window-maximum/", "article_url": "https://takeuforward.org/data-structure/sliding-window-maximum/", "problem_slug": "sliding-window-maximum", "description": "Find maximum element in every window of size k."},

    # Day 15 & 16: Strings
    {"pattern": "Day 15 & 16: Strings", "position": 1, "title": "Reverse Words in a String", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/reverse-words-in-a-string/", "article_url": "https://takeuforward.org/data-structure/reverse-words-in-a-string/", "description": "Reverse word order in a given string."},
    {"pattern": "Day 15 & 16: Strings", "position": 2, "title": "Longest Palindromic Substring", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/longest-palindromic-substring/", "article_url": "https://takeuforward.org/data-structure/longest-palindromic-substring/", "description": "Find longest palindromic substring."},
    {"pattern": "Day 15 & 16: Strings", "position": 3, "title": "Valid Anagram", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/valid-anagram/", "article_url": "https://takeuforward.org/data-structure/check-if-two-strings-are-anagrams-of-each-other/", "problem_slug": "valid-anagram", "description": "Check whether two strings are anagrams."},

    # Day 17 - 19: Binary Trees
    {"pattern": "Day 17 - 19: Binary Trees", "position": 1, "title": "Binary Tree Traversals (Inorder, Preorder, Postorder)", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/binary-tree-inorder-traversal/", "article_url": "https://takeuforward.org/data-structure/inorder-traversal-of-binary-tree/", "description": "Perform tree traversals iteratively and recursively."},
    {"pattern": "Day 17 - 19: Binary Trees", "position": 2, "title": "Level Order Traversal", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/binary-tree-level-order-traversal/", "article_url": "https://takeuforward.org/data-structure/level-order-traversal-of-a-binary-tree/", "description": "Return level order traversal of binary tree node values."},
    {"pattern": "Day 17 - 19: Binary Trees", "position": 3, "title": "Maximum Depth of Binary Tree", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "article_url": "https://takeuforward.org/data-structure/maximum-depth-of-a-binary-tree/", "description": "Find height / maximum depth of binary tree."},
    {"pattern": "Day 17 - 19: Binary Trees", "position": 4, "title": "Diameter of Binary Tree", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/diameter-of-binary-tree/", "article_url": "https://takeuforward.org/data-structure/calculate-the-diameter-of-a-binary-tree/", "description": "Calculate longest path length between any two nodes in tree."},
    {"pattern": "Day 17 - 19: Binary Trees", "position": 5, "title": "Lowest Common Ancestor (LCA) in Binary Tree", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "article_url": "https://takeuforward.org/data-structure/lowest-common-ancestor-for-two-given-nodes-in-binary-tree/", "description": "Find lowest common ancestor node for two given tree nodes."},

    # Day 20 - 21: Binary Search Trees
    {"pattern": "Day 20 - 21: Binary Search Trees", "position": 1, "title": "Search in a Binary Search Tree", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/search-in-a-binary-search-tree/", "article_url": "https://takeuforward.org/data-structure/search-in-a-binary-search-tree/", "description": "Search for a node value in a BST."},
    {"pattern": "Day 20 - 21: Binary Search Trees", "position": 2, "title": "Validate Binary Search Tree", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/validate-binary-search-tree/", "article_url": "https://takeuforward.org/data-structure/check-if-a-tree-is-a-bst-or-bt/", "description": "Determine if a binary tree is a valid binary search tree."},
    {"pattern": "Day 20 - 21: Binary Search Trees", "position": 3, "title": "Kth Smallest Element in a BST", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "article_url": "https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree-bst/", "problem_slug": "kth-smallest-in-bst", "description": "Find kth smallest element in a BST."},

    # Day 23 & 24: Graph Algorithms
    {"pattern": "Day 23 & 24: Graph Algorithms", "position": 1, "title": "BFS & DFS Traversal of Graph", "difficulty": "easy", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1", "article_url": "https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/", "description": "Perform BFS and DFS traversal of undirected graph."},
    {"pattern": "Day 23 & 24: Graph Algorithms", "position": 2, "title": "Number of Islands", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/number-of-islands/", "article_url": "https://takeuforward.org/data-structure/number-of-islands/", "problem_slug": "number-of-islands", "description": "Count connected components of 1s in a 2D grid."},
    {"pattern": "Day 23 & 24: Graph Algorithms", "position": 3, "title": "Course Schedule (Topological Sort)", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/course-schedule/", "article_url": "https://takeuforward.org/data-structure/topological-sort-bfs-kahns-algorithm/", "problem_slug": "course-schedule", "description": "Detect cycle in directed graph / Kahn's Topological Sort."},
    {"pattern": "Day 23 & 24: Graph Algorithms", "position": 4, "title": "Dijkstra's Shortest Path Algorithm", "difficulty": "medium", "platform": "gfg", "problem_url": "https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1", "article_url": "https://takeuforward.org/data-structure/dijkstras-algorithm-shortest-distance-to-all-nodes-from-source-using-priority-queue-g-32/", "description": "Find shortest path from source node using priority queue."},

    # Day 25 & 26: Dynamic Programming
    {"pattern": "Day 25 & 26: Dynamic Programming", "position": 1, "title": "Climbing Stairs", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/climbing-stairs/", "article_url": "https://takeuforward.org/data-structure/dynamic-programming-climbing-stairs/", "problem_slug": "climbing-stairs", "description": "Count distinct ways to climb n stairs taking 1 or 2 steps."},
    {"pattern": "Day 25 & 26: Dynamic Programming", "position": 2, "title": "Coin Change", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/coin-change/", "article_url": "https://takeuforward.org/data-structure/coin-change-2-dp-22/", "problem_slug": "coin-change", "description": "Find fewest coins needed to make up a given amount."},
    {"pattern": "Day 25 & 26: Dynamic Programming", "position": 3, "title": "Longest Increasing Subsequence", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/longest-increasing-subsequence/", "article_url": "https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/", "problem_slug": "longest-increasing-subsequence", "description": "Find length of longest strictly increasing subsequence."},
    {"pattern": "Day 25 & 26: Dynamic Programming", "position": 4, "title": "Edit Distance", "difficulty": "hard", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/edit-distance/", "article_url": "https://takeuforward.org/data-structure/edit-distance-dp-33/", "problem_slug": "edit-distance", "description": "Find minimum insertions, deletions, and replacements to convert word1 to word2."},
]

FRAZ_SHEET_ITEMS = [
    {"pattern": "Array & Two Pointers", "position": 1, "title": "Two Sum", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/two-sum/", "article_url": "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/", "problem_slug": "two-sum", "description": "Check if pair with target sum exists."},
    {"pattern": "Array & Two Pointers", "position": 2, "title": "Best Time to Buy and Sell Stock", "difficulty": "easy", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "article_url": "https://takeuforward.org/data-structure/stock-buy-and-sell/", "problem_slug": "best-time-to-buy-and-sell-stock", "description": "Maximize single buy-sell profit."},
    {"pattern": "Array & Two Pointers", "position": 3, "title": "Container With Most Water", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/container-with-most-water/", "article_url": "https://takeuforward.org/data-structure/container-with-most-water/", "problem_slug": "container-with-most-water", "description": "Find maximum water storage container."},
    {"pattern": "Prefix Sum & Hash Table", "position": 1, "title": "Subarray Sum Equals K", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/subarray-sum-equals-k/", "article_url": "https://takeuforward.org/data-structure/count-subarray-sum-equals-k/", "problem_slug": "subarray-sum-equals-k", "description": "Count contiguous subarrays with sum equal to k."},
    {"pattern": "Prefix Sum & Hash Table", "position": 2, "title": "Product of Array Except Self", "difficulty": "medium", "platform": "leetcode", "problem_url": "https://leetcode.com/problems/product-of-array-except-self/", "article_url": "https://takeuforward.org/data-structure/product-of-array-except-self/", "description": "Calculate product array without division."},
]

SHEETS_DATA = [
    {
        "slug": "strivers-sde-pattern-sheet",
        "title": "Striver's SDE Sheet (Complete Day 1-27)",
        "author": "TakeUForward (Striver)",
        "description": "The complete official Striver's SDE Sheet (Days 1 to 27). Every problem includes direct LeetCode, Codeforces, GeeksforGeeks, and TakeUForward article links with interactive checkmark solve tracking.",
        "items": STRIVERS_SDE_SHEET_ITEMS,
    },
    {
        "slug": "fraz-75-essential-sheet",
        "title": "Fraz's 75 Essential SDE Sheet",
        "author": "Mohammad Fraz",
        "description": "75 essential coding questions organized for quick revision before tech interviews with solve tracking.",
        "items": FRAZ_SHEET_ITEMS,
    },
]


async def seed_sheets(db: AsyncSession) -> None:
    existing = await db.execute(select(Sheet).options(selectinload(Sheet.items)))
    existing_by_slug = {sheet.slug: sheet for sheet in existing.scalars().all()}

    for sheet_data in SHEETS_DATA:
        items_data = sheet_data["items"]
        sheet = existing_by_slug.get(sheet_data["slug"])

        if sheet is None:
            sheet = Sheet(slug=sheet_data["slug"])
            db.add(sheet)

        sheet.title = sheet_data["title"]
        sheet.author = sheet_data["author"]
        sheet.description = sheet_data["description"]

        had_items = bool(sheet.items)
        sheet.items.clear()
        if had_items:
            await db.flush()

        for item_info in items_data:
            sheet.items.append(
                SheetItem(
                    pattern=item_info["pattern"],
                    position=item_info["position"],
                    title=item_info["title"],
                    difficulty=item_info["difficulty"],
                    platform=item_info["platform"],
                    problem_url=item_info["problem_url"],
                    article_url=item_info.get("article_url"),
                    problem_slug=item_info.get("problem_slug"),
                    description=item_info.get("description"),
                )
            )

    await db.commit()
